// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package NetPacket;

public final class PacketOuterClass {
  private PacketOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetPacket.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string route = 1;</code>
     */
    boolean hasRoute();
    /**
     * <code>required string route = 1;</code>
     */
    java.lang.String getRoute();
    /**
     * <code>required string route = 1;</code>
     */
    com.google.protobuf.ByteString
        getRouteBytes();

    /**
     * <pre>
     *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
     * </pre>
     *
     * <code>repeated int32 paramTypeList = 2;</code>
     */
    java.util.List<java.lang.Integer> getParamTypeListList();
    /**
     * <pre>
     *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
     * </pre>
     *
     * <code>repeated int32 paramTypeList = 2;</code>
     */
    int getParamTypeListCount();
    /**
     * <pre>
     *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
     * </pre>
     *
     * <code>repeated int32 paramTypeList = 2;</code>
     */
    int getParamTypeList(int index);

    /**
     * <code>repeated double double = 3;</code>
     */
    java.util.List<java.lang.Double> getDoubleList();
    /**
     * <code>repeated double double = 3;</code>
     */
    int getDoubleCount();
    /**
     * <code>repeated double double = 3;</code>
     */
    double getDouble(int index);

    /**
     * <code>repeated float float = 4;</code>
     */
    java.util.List<java.lang.Float> getFloatList();
    /**
     * <code>repeated float float = 4;</code>
     */
    int getFloatCount();
    /**
     * <code>repeated float float = 4;</code>
     */
    float getFloat(int index);

    /**
     * <code>repeated sint32 sint32 = 5;</code>
     */
    java.util.List<java.lang.Integer> getSint32List();
    /**
     * <code>repeated sint32 sint32 = 5;</code>
     */
    int getSint32Count();
    /**
     * <code>repeated sint32 sint32 = 5;</code>
     */
    int getSint32(int index);

    /**
     * <code>repeated sint64 sint64 = 6;</code>
     */
    java.util.List<java.lang.Long> getSint64List();
    /**
     * <code>repeated sint64 sint64 = 6;</code>
     */
    int getSint64Count();
    /**
     * <code>repeated sint64 sint64 = 6;</code>
     */
    long getSint64(int index);

    /**
     * <code>repeated bool bool = 7;</code>
     */
    java.util.List<java.lang.Boolean> getBoolList();
    /**
     * <code>repeated bool bool = 7;</code>
     */
    int getBoolCount();
    /**
     * <code>repeated bool bool = 7;</code>
     */
    boolean getBool(int index);

    /**
     * <code>repeated string string = 8;</code>
     */
    java.util.List<java.lang.String>
        getStringList();
    /**
     * <code>repeated string string = 8;</code>
     */
    int getStringCount();
    /**
     * <code>repeated string string = 8;</code>
     */
    java.lang.String getString(int index);
    /**
     * <code>repeated string string = 8;</code>
     */
    com.google.protobuf.ByteString
        getStringBytes(int index);
  }
  /**
   * Protobuf type {@code NetPacket.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NetPacket.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      route_ = "";
      paramTypeList_ = java.util.Collections.emptyList();
      double_ = java.util.Collections.emptyList();
      float_ = java.util.Collections.emptyList();
      sint32_ = java.util.Collections.emptyList();
      sint64_ = java.util.Collections.emptyList();
      bool_ = java.util.Collections.emptyList();
      string_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              route_ = bs;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                paramTypeList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              paramTypeList_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                paramTypeList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                paramTypeList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 25: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                double_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              double_.add(input.readDouble());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                double_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                double_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 37: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                float_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000008;
              }
              float_.add(input.readFloat());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                float_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                float_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                sint32_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              sint32_.add(input.readSInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                sint32_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                sint32_.add(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                sint64_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000020;
              }
              sint64_.add(input.readSInt64());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                sint64_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                sint64_.add(input.readSInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                bool_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000040;
              }
              bool_.add(input.readBool());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                bool_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                bool_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                string_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              string_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          paramTypeList_ = java.util.Collections.unmodifiableList(paramTypeList_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          double_ = java.util.Collections.unmodifiableList(double_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          float_ = java.util.Collections.unmodifiableList(float_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          sint32_ = java.util.Collections.unmodifiableList(sint32_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          sint64_ = java.util.Collections.unmodifiableList(sint64_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          bool_ = java.util.Collections.unmodifiableList(bool_);
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          string_ = string_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetPacket.PacketOuterClass.internal_static_NetPacket_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetPacket.PacketOuterClass.internal_static_NetPacket_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetPacket.PacketOuterClass.Packet.class, NetPacket.PacketOuterClass.Packet.Builder.class);
    }

    private int bitField0_;
    public static final int ROUTE_FIELD_NUMBER = 1;
    private volatile java.lang.Object route_;
    /**
     * <code>required string route = 1;</code>
     */
    public boolean hasRoute() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string route = 1;</code>
     */
    public java.lang.String getRoute() {
      java.lang.Object ref = route_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          route_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string route = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRouteBytes() {
      java.lang.Object ref = route_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        route_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMTYPELIST_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> paramTypeList_;
    /**
     * <pre>
     *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
     * </pre>
     *
     * <code>repeated int32 paramTypeList = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getParamTypeListList() {
      return paramTypeList_;
    }
    /**
     * <pre>
     *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
     * </pre>
     *
     * <code>repeated int32 paramTypeList = 2;</code>
     */
    public int getParamTypeListCount() {
      return paramTypeList_.size();
    }
    /**
     * <pre>
     *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
     * </pre>
     *
     * <code>repeated int32 paramTypeList = 2;</code>
     */
    public int getParamTypeList(int index) {
      return paramTypeList_.get(index);
    }

    public static final int DOUBLE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Double> double_;
    /**
     * <code>repeated double double = 3;</code>
     */
    public java.util.List<java.lang.Double>
        getDoubleList() {
      return double_;
    }
    /**
     * <code>repeated double double = 3;</code>
     */
    public int getDoubleCount() {
      return double_.size();
    }
    /**
     * <code>repeated double double = 3;</code>
     */
    public double getDouble(int index) {
      return double_.get(index);
    }

    public static final int FLOAT_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Float> float_;
    /**
     * <code>repeated float float = 4;</code>
     */
    public java.util.List<java.lang.Float>
        getFloatList() {
      return float_;
    }
    /**
     * <code>repeated float float = 4;</code>
     */
    public int getFloatCount() {
      return float_.size();
    }
    /**
     * <code>repeated float float = 4;</code>
     */
    public float getFloat(int index) {
      return float_.get(index);
    }

    public static final int SINT32_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> sint32_;
    /**
     * <code>repeated sint32 sint32 = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getSint32List() {
      return sint32_;
    }
    /**
     * <code>repeated sint32 sint32 = 5;</code>
     */
    public int getSint32Count() {
      return sint32_.size();
    }
    /**
     * <code>repeated sint32 sint32 = 5;</code>
     */
    public int getSint32(int index) {
      return sint32_.get(index);
    }

    public static final int SINT64_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Long> sint64_;
    /**
     * <code>repeated sint64 sint64 = 6;</code>
     */
    public java.util.List<java.lang.Long>
        getSint64List() {
      return sint64_;
    }
    /**
     * <code>repeated sint64 sint64 = 6;</code>
     */
    public int getSint64Count() {
      return sint64_.size();
    }
    /**
     * <code>repeated sint64 sint64 = 6;</code>
     */
    public long getSint64(int index) {
      return sint64_.get(index);
    }

    public static final int BOOL_FIELD_NUMBER = 7;
    private java.util.List<java.lang.Boolean> bool_;
    /**
     * <code>repeated bool bool = 7;</code>
     */
    public java.util.List<java.lang.Boolean>
        getBoolList() {
      return bool_;
    }
    /**
     * <code>repeated bool bool = 7;</code>
     */
    public int getBoolCount() {
      return bool_.size();
    }
    /**
     * <code>repeated bool bool = 7;</code>
     */
    public boolean getBool(int index) {
      return bool_.get(index);
    }

    public static final int STRING_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList string_;
    /**
     * <code>repeated string string = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStringList() {
      return string_;
    }
    /**
     * <code>repeated string string = 8;</code>
     */
    public int getStringCount() {
      return string_.size();
    }
    /**
     * <code>repeated string string = 8;</code>
     */
    public java.lang.String getString(int index) {
      return string_.get(index);
    }
    /**
     * <code>repeated string string = 8;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes(int index) {
      return string_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRoute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, route_);
      }
      for (int i = 0; i < paramTypeList_.size(); i++) {
        output.writeInt32(2, paramTypeList_.get(i));
      }
      for (int i = 0; i < double_.size(); i++) {
        output.writeDouble(3, double_.get(i));
      }
      for (int i = 0; i < float_.size(); i++) {
        output.writeFloat(4, float_.get(i));
      }
      for (int i = 0; i < sint32_.size(); i++) {
        output.writeSInt32(5, sint32_.get(i));
      }
      for (int i = 0; i < sint64_.size(); i++) {
        output.writeSInt64(6, sint64_.get(i));
      }
      for (int i = 0; i < bool_.size(); i++) {
        output.writeBool(7, bool_.get(i));
      }
      for (int i = 0; i < string_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, string_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, route_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramTypeList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(paramTypeList_.get(i));
        }
        size += dataSize;
        size += 1 * getParamTypeListList().size();
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDoubleList().size();
        size += dataSize;
        size += 1 * getDoubleList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getFloatList().size();
        size += dataSize;
        size += 1 * getFloatList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sint32_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(sint32_.get(i));
        }
        size += dataSize;
        size += 1 * getSint32List().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sint64_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt64SizeNoTag(sint64_.get(i));
        }
        size += dataSize;
        size += 1 * getSint64List().size();
      }
      {
        int dataSize = 0;
        dataSize = 1 * getBoolList().size();
        size += dataSize;
        size += 1 * getBoolList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < string_.size(); i++) {
          dataSize += computeStringSizeNoTag(string_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStringList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NetPacket.PacketOuterClass.Packet)) {
        return super.equals(obj);
      }
      NetPacket.PacketOuterClass.Packet other = (NetPacket.PacketOuterClass.Packet) obj;

      boolean result = true;
      result = result && (hasRoute() == other.hasRoute());
      if (hasRoute()) {
        result = result && getRoute()
            .equals(other.getRoute());
      }
      result = result && getParamTypeListList()
          .equals(other.getParamTypeListList());
      result = result && getDoubleList()
          .equals(other.getDoubleList());
      result = result && getFloatList()
          .equals(other.getFloatList());
      result = result && getSint32List()
          .equals(other.getSint32List());
      result = result && getSint64List()
          .equals(other.getSint64List());
      result = result && getBoolList()
          .equals(other.getBoolList());
      result = result && getStringList()
          .equals(other.getStringList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRoute()) {
        hash = (37 * hash) + ROUTE_FIELD_NUMBER;
        hash = (53 * hash) + getRoute().hashCode();
      }
      if (getParamTypeListCount() > 0) {
        hash = (37 * hash) + PARAMTYPELIST_FIELD_NUMBER;
        hash = (53 * hash) + getParamTypeListList().hashCode();
      }
      if (getDoubleCount() > 0) {
        hash = (37 * hash) + DOUBLE_FIELD_NUMBER;
        hash = (53 * hash) + getDoubleList().hashCode();
      }
      if (getFloatCount() > 0) {
        hash = (37 * hash) + FLOAT_FIELD_NUMBER;
        hash = (53 * hash) + getFloatList().hashCode();
      }
      if (getSint32Count() > 0) {
        hash = (37 * hash) + SINT32_FIELD_NUMBER;
        hash = (53 * hash) + getSint32List().hashCode();
      }
      if (getSint64Count() > 0) {
        hash = (37 * hash) + SINT64_FIELD_NUMBER;
        hash = (53 * hash) + getSint64List().hashCode();
      }
      if (getBoolCount() > 0) {
        hash = (37 * hash) + BOOL_FIELD_NUMBER;
        hash = (53 * hash) + getBoolList().hashCode();
      }
      if (getStringCount() > 0) {
        hash = (37 * hash) + STRING_FIELD_NUMBER;
        hash = (53 * hash) + getStringList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NetPacket.PacketOuterClass.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NetPacket.PacketOuterClass.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NetPacket.PacketOuterClass.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NetPacket.PacketOuterClass.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NetPacket.PacketOuterClass.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetPacket.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetPacket.Packet)
        NetPacket.PacketOuterClass.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetPacket.PacketOuterClass.internal_static_NetPacket_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetPacket.PacketOuterClass.internal_static_NetPacket_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetPacket.PacketOuterClass.Packet.class, NetPacket.PacketOuterClass.Packet.Builder.class);
      }

      // Construct using NetPacket.PacketOuterClass.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        route_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        paramTypeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        double_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        float_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        sint32_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        sint64_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        bool_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        string_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetPacket.PacketOuterClass.internal_static_NetPacket_Packet_descriptor;
      }

      public NetPacket.PacketOuterClass.Packet getDefaultInstanceForType() {
        return NetPacket.PacketOuterClass.Packet.getDefaultInstance();
      }

      public NetPacket.PacketOuterClass.Packet build() {
        NetPacket.PacketOuterClass.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetPacket.PacketOuterClass.Packet buildPartial() {
        NetPacket.PacketOuterClass.Packet result = new NetPacket.PacketOuterClass.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.route_ = route_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          paramTypeList_ = java.util.Collections.unmodifiableList(paramTypeList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.paramTypeList_ = paramTypeList_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          double_ = java.util.Collections.unmodifiableList(double_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.double_ = double_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          float_ = java.util.Collections.unmodifiableList(float_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.float_ = float_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          sint32_ = java.util.Collections.unmodifiableList(sint32_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.sint32_ = sint32_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          sint64_ = java.util.Collections.unmodifiableList(sint64_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.sint64_ = sint64_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          bool_ = java.util.Collections.unmodifiableList(bool_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.bool_ = bool_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          string_ = string_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.string_ = string_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetPacket.PacketOuterClass.Packet) {
          return mergeFrom((NetPacket.PacketOuterClass.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetPacket.PacketOuterClass.Packet other) {
        if (other == NetPacket.PacketOuterClass.Packet.getDefaultInstance()) return this;
        if (other.hasRoute()) {
          bitField0_ |= 0x00000001;
          route_ = other.route_;
          onChanged();
        }
        if (!other.paramTypeList_.isEmpty()) {
          if (paramTypeList_.isEmpty()) {
            paramTypeList_ = other.paramTypeList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParamTypeListIsMutable();
            paramTypeList_.addAll(other.paramTypeList_);
          }
          onChanged();
        }
        if (!other.double_.isEmpty()) {
          if (double_.isEmpty()) {
            double_ = other.double_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDoubleIsMutable();
            double_.addAll(other.double_);
          }
          onChanged();
        }
        if (!other.float_.isEmpty()) {
          if (float_.isEmpty()) {
            float_ = other.float_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFloatIsMutable();
            float_.addAll(other.float_);
          }
          onChanged();
        }
        if (!other.sint32_.isEmpty()) {
          if (sint32_.isEmpty()) {
            sint32_ = other.sint32_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSint32IsMutable();
            sint32_.addAll(other.sint32_);
          }
          onChanged();
        }
        if (!other.sint64_.isEmpty()) {
          if (sint64_.isEmpty()) {
            sint64_ = other.sint64_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureSint64IsMutable();
            sint64_.addAll(other.sint64_);
          }
          onChanged();
        }
        if (!other.bool_.isEmpty()) {
          if (bool_.isEmpty()) {
            bool_ = other.bool_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureBoolIsMutable();
            bool_.addAll(other.bool_);
          }
          onChanged();
        }
        if (!other.string_.isEmpty()) {
          if (string_.isEmpty()) {
            string_ = other.string_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureStringIsMutable();
            string_.addAll(other.string_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoute()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetPacket.PacketOuterClass.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetPacket.PacketOuterClass.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object route_ = "";
      /**
       * <code>required string route = 1;</code>
       */
      public boolean hasRoute() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string route = 1;</code>
       */
      public java.lang.String getRoute() {
        java.lang.Object ref = route_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            route_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string route = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRouteBytes() {
        java.lang.Object ref = route_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          route_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string route = 1;</code>
       */
      public Builder setRoute(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        route_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string route = 1;</code>
       */
      public Builder clearRoute() {
        bitField0_ = (bitField0_ & ~0x00000001);
        route_ = getDefaultInstance().getRoute();
        onChanged();
        return this;
      }
      /**
       * <code>required string route = 1;</code>
       */
      public Builder setRouteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        route_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> paramTypeList_ = java.util.Collections.emptyList();
      private void ensureParamTypeListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          paramTypeList_ = new java.util.ArrayList<java.lang.Integer>(paramTypeList_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
       * </pre>
       *
       * <code>repeated int32 paramTypeList = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getParamTypeListList() {
        return java.util.Collections.unmodifiableList(paramTypeList_);
      }
      /**
       * <pre>
       *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
       * </pre>
       *
       * <code>repeated int32 paramTypeList = 2;</code>
       */
      public int getParamTypeListCount() {
        return paramTypeList_.size();
      }
      /**
       * <pre>
       *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
       * </pre>
       *
       * <code>repeated int32 paramTypeList = 2;</code>
       */
      public int getParamTypeList(int index) {
        return paramTypeList_.get(index);
      }
      /**
       * <pre>
       *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
       * </pre>
       *
       * <code>repeated int32 paramTypeList = 2;</code>
       */
      public Builder setParamTypeList(
          int index, int value) {
        ensureParamTypeListIsMutable();
        paramTypeList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
       * </pre>
       *
       * <code>repeated int32 paramTypeList = 2;</code>
       */
      public Builder addParamTypeList(int value) {
        ensureParamTypeListIsMutable();
        paramTypeList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
       * </pre>
       *
       * <code>repeated int32 paramTypeList = 2;</code>
       */
      public Builder addAllParamTypeList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureParamTypeListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramTypeList_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0:double 1:float 2:sint32 3:sint64 4:bool 5:string
       * </pre>
       *
       * <code>repeated int32 paramTypeList = 2;</code>
       */
      public Builder clearParamTypeList() {
        paramTypeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> double_ = java.util.Collections.emptyList();
      private void ensureDoubleIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          double_ = new java.util.ArrayList<java.lang.Double>(double_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated double double = 3;</code>
       */
      public java.util.List<java.lang.Double>
          getDoubleList() {
        return java.util.Collections.unmodifiableList(double_);
      }
      /**
       * <code>repeated double double = 3;</code>
       */
      public int getDoubleCount() {
        return double_.size();
      }
      /**
       * <code>repeated double double = 3;</code>
       */
      public double getDouble(int index) {
        return double_.get(index);
      }
      /**
       * <code>repeated double double = 3;</code>
       */
      public Builder setDouble(
          int index, double value) {
        ensureDoubleIsMutable();
        double_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double double = 3;</code>
       */
      public Builder addDouble(double value) {
        ensureDoubleIsMutable();
        double_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double double = 3;</code>
       */
      public Builder addAllDouble(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDoubleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, double_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double double = 3;</code>
       */
      public Builder clearDouble() {
        double_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> float_ = java.util.Collections.emptyList();
      private void ensureFloatIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          float_ = new java.util.ArrayList<java.lang.Float>(float_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated float float = 4;</code>
       */
      public java.util.List<java.lang.Float>
          getFloatList() {
        return java.util.Collections.unmodifiableList(float_);
      }
      /**
       * <code>repeated float float = 4;</code>
       */
      public int getFloatCount() {
        return float_.size();
      }
      /**
       * <code>repeated float float = 4;</code>
       */
      public float getFloat(int index) {
        return float_.get(index);
      }
      /**
       * <code>repeated float float = 4;</code>
       */
      public Builder setFloat(
          int index, float value) {
        ensureFloatIsMutable();
        float_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float float = 4;</code>
       */
      public Builder addFloat(float value) {
        ensureFloatIsMutable();
        float_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float float = 4;</code>
       */
      public Builder addAllFloat(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureFloatIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, float_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float float = 4;</code>
       */
      public Builder clearFloat() {
        float_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> sint32_ = java.util.Collections.emptyList();
      private void ensureSint32IsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          sint32_ = new java.util.ArrayList<java.lang.Integer>(sint32_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated sint32 sint32 = 5;</code>
       */
      public java.util.List<java.lang.Integer>
          getSint32List() {
        return java.util.Collections.unmodifiableList(sint32_);
      }
      /**
       * <code>repeated sint32 sint32 = 5;</code>
       */
      public int getSint32Count() {
        return sint32_.size();
      }
      /**
       * <code>repeated sint32 sint32 = 5;</code>
       */
      public int getSint32(int index) {
        return sint32_.get(index);
      }
      /**
       * <code>repeated sint32 sint32 = 5;</code>
       */
      public Builder setSint32(
          int index, int value) {
        ensureSint32IsMutable();
        sint32_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 sint32 = 5;</code>
       */
      public Builder addSint32(int value) {
        ensureSint32IsMutable();
        sint32_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 sint32 = 5;</code>
       */
      public Builder addAllSint32(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSint32IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sint32_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 sint32 = 5;</code>
       */
      public Builder clearSint32() {
        sint32_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> sint64_ = java.util.Collections.emptyList();
      private void ensureSint64IsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          sint64_ = new java.util.ArrayList<java.lang.Long>(sint64_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated sint64 sint64 = 6;</code>
       */
      public java.util.List<java.lang.Long>
          getSint64List() {
        return java.util.Collections.unmodifiableList(sint64_);
      }
      /**
       * <code>repeated sint64 sint64 = 6;</code>
       */
      public int getSint64Count() {
        return sint64_.size();
      }
      /**
       * <code>repeated sint64 sint64 = 6;</code>
       */
      public long getSint64(int index) {
        return sint64_.get(index);
      }
      /**
       * <code>repeated sint64 sint64 = 6;</code>
       */
      public Builder setSint64(
          int index, long value) {
        ensureSint64IsMutable();
        sint64_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint64 sint64 = 6;</code>
       */
      public Builder addSint64(long value) {
        ensureSint64IsMutable();
        sint64_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint64 sint64 = 6;</code>
       */
      public Builder addAllSint64(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSint64IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sint64_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint64 sint64 = 6;</code>
       */
      public Builder clearSint64() {
        sint64_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Boolean> bool_ = java.util.Collections.emptyList();
      private void ensureBoolIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          bool_ = new java.util.ArrayList<java.lang.Boolean>(bool_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated bool bool = 7;</code>
       */
      public java.util.List<java.lang.Boolean>
          getBoolList() {
        return java.util.Collections.unmodifiableList(bool_);
      }
      /**
       * <code>repeated bool bool = 7;</code>
       */
      public int getBoolCount() {
        return bool_.size();
      }
      /**
       * <code>repeated bool bool = 7;</code>
       */
      public boolean getBool(int index) {
        return bool_.get(index);
      }
      /**
       * <code>repeated bool bool = 7;</code>
       */
      public Builder setBool(
          int index, boolean value) {
        ensureBoolIsMutable();
        bool_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bool = 7;</code>
       */
      public Builder addBool(boolean value) {
        ensureBoolIsMutable();
        bool_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bool = 7;</code>
       */
      public Builder addAllBool(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureBoolIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bool_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bool = 7;</code>
       */
      public Builder clearBool() {
        bool_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList string_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          string_ = new com.google.protobuf.LazyStringArrayList(string_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStringList() {
        return string_.getUnmodifiableView();
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public int getStringCount() {
        return string_.size();
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public java.lang.String getString(int index) {
        return string_.get(index);
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public com.google.protobuf.ByteString
          getStringBytes(int index) {
        return string_.getByteString(index);
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public Builder setString(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringIsMutable();
        string_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public Builder addString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringIsMutable();
        string_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public Builder addAllString(
          java.lang.Iterable<java.lang.String> values) {
        ensureStringIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, string_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public Builder clearString() {
        string_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string string = 8;</code>
       */
      public Builder addStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringIsMutable();
        string_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NetPacket.Packet)
    }

    // @@protoc_insertion_point(class_scope:NetPacket.Packet)
    private static final NetPacket.PacketOuterClass.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NetPacket.PacketOuterClass.Packet();
    }

    public static NetPacket.PacketOuterClass.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public NetPacket.PacketOuterClass.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetPacket_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NetPacket_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\022\tNetPacket\032\014common.proto\"" +
      "\213\001\n\006Packet\022\r\n\005route\030\001 \002(\t\022\025\n\rparamTypeLi" +
      "st\030\002 \003(\005\022\016\n\006double\030\003 \003(\001\022\r\n\005float\030\004 \003(\002\022" +
      "\016\n\006sint32\030\005 \003(\021\022\016\n\006sint64\030\006 \003(\022\022\014\n\004bool\030" +
      "\007 \003(\010\022\016\n\006string\030\010 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          test.CommonOuterClass.getDescriptor(),
        }, assigner);
    internal_static_NetPacket_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NetPacket_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NetPacket_Packet_descriptor,
        new java.lang.String[] { "Route", "ParamTypeList", "Double", "Float", "Sint32", "Sint64", "Bool", "String", });
    test.CommonOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
