// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet2.proto

package test;

public final class Packet2 {
  private Packet2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Test2RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.Test2Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 testId = 1;</code>
     */
    int getTestId();
  }
  /**
   * Protobuf type {@code test.Test2Request}
   */
  public  static final class Test2Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.Test2Request)
      Test2RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Test2Request.newBuilder() to construct.
    private Test2Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test2Request() {
      testId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Test2Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              testId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.Packet2.internal_static_test_Test2Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.Packet2.internal_static_test_Test2Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.Packet2.Test2Request.class, test.Packet2.Test2Request.Builder.class);
    }

    public static final int TESTID_FIELD_NUMBER = 1;
    private int testId_;
    /**
     * <code>int32 testId = 1;</code>
     */
    public int getTestId() {
      return testId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (testId_ != 0) {
        output.writeInt32(1, testId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (testId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, testId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.Packet2.Test2Request)) {
        return super.equals(obj);
      }
      test.Packet2.Test2Request other = (test.Packet2.Test2Request) obj;

      boolean result = true;
      result = result && (getTestId()
          == other.getTestId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TESTID_FIELD_NUMBER;
      hash = (53 * hash) + getTestId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.Packet2.Test2Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Packet2.Test2Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Packet2.Test2Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Packet2.Test2Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Packet2.Test2Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Packet2.Test2Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Packet2.Test2Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.Packet2.Test2Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.Packet2.Test2Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.Packet2.Test2Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.Packet2.Test2Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.Packet2.Test2Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.Packet2.Test2Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Test2Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.Test2Request)
        test.Packet2.Test2RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.Packet2.internal_static_test_Test2Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.Packet2.internal_static_test_Test2Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.Packet2.Test2Request.class, test.Packet2.Test2Request.Builder.class);
      }

      // Construct using test.Packet2.Test2Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        testId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.Packet2.internal_static_test_Test2Request_descriptor;
      }

      public test.Packet2.Test2Request getDefaultInstanceForType() {
        return test.Packet2.Test2Request.getDefaultInstance();
      }

      public test.Packet2.Test2Request build() {
        test.Packet2.Test2Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public test.Packet2.Test2Request buildPartial() {
        test.Packet2.Test2Request result = new test.Packet2.Test2Request(this);
        result.testId_ = testId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.Packet2.Test2Request) {
          return mergeFrom((test.Packet2.Test2Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.Packet2.Test2Request other) {
        if (other == test.Packet2.Test2Request.getDefaultInstance()) return this;
        if (other.getTestId() != 0) {
          setTestId(other.getTestId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.Packet2.Test2Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.Packet2.Test2Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int testId_ ;
      /**
       * <code>int32 testId = 1;</code>
       */
      public int getTestId() {
        return testId_;
      }
      /**
       * <code>int32 testId = 1;</code>
       */
      public Builder setTestId(int value) {
        
        testId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 testId = 1;</code>
       */
      public Builder clearTestId() {
        
        testId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.Test2Request)
    }

    // @@protoc_insertion_point(class_scope:test.Test2Request)
    private static final test.Packet2.Test2Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.Packet2.Test2Request();
    }

    public static test.Packet2.Test2Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test2Request>
        PARSER = new com.google.protobuf.AbstractParser<Test2Request>() {
      public Test2Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test2Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test2Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test2Request> getParserForType() {
      return PARSER;
    }

    public test.Packet2.Test2Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Test2ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.Test2Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.common.CommonNode testCommonNode = 1;</code>
     */
    boolean hasTestCommonNode();
    /**
     * <code>.common.CommonNode testCommonNode = 1;</code>
     */
    common.Common.CommonNode getTestCommonNode();
    /**
     * <code>.common.CommonNode testCommonNode = 1;</code>
     */
    common.Common.CommonNodeOrBuilder getTestCommonNodeOrBuilder();
  }
  /**
   * Protobuf type {@code test.Test2Response}
   */
  public  static final class Test2Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.Test2Response)
      Test2ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Test2Response.newBuilder() to construct.
    private Test2Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test2Response() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Test2Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              common.Common.CommonNode.Builder subBuilder = null;
              if (testCommonNode_ != null) {
                subBuilder = testCommonNode_.toBuilder();
              }
              testCommonNode_ = input.readMessage(common.Common.CommonNode.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(testCommonNode_);
                testCommonNode_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.Packet2.internal_static_test_Test2Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.Packet2.internal_static_test_Test2Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.Packet2.Test2Response.class, test.Packet2.Test2Response.Builder.class);
    }

    public static final int TESTCOMMONNODE_FIELD_NUMBER = 1;
    private common.Common.CommonNode testCommonNode_;
    /**
     * <code>.common.CommonNode testCommonNode = 1;</code>
     */
    public boolean hasTestCommonNode() {
      return testCommonNode_ != null;
    }
    /**
     * <code>.common.CommonNode testCommonNode = 1;</code>
     */
    public common.Common.CommonNode getTestCommonNode() {
      return testCommonNode_ == null ? common.Common.CommonNode.getDefaultInstance() : testCommonNode_;
    }
    /**
     * <code>.common.CommonNode testCommonNode = 1;</code>
     */
    public common.Common.CommonNodeOrBuilder getTestCommonNodeOrBuilder() {
      return getTestCommonNode();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (testCommonNode_ != null) {
        output.writeMessage(1, getTestCommonNode());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (testCommonNode_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTestCommonNode());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.Packet2.Test2Response)) {
        return super.equals(obj);
      }
      test.Packet2.Test2Response other = (test.Packet2.Test2Response) obj;

      boolean result = true;
      result = result && (hasTestCommonNode() == other.hasTestCommonNode());
      if (hasTestCommonNode()) {
        result = result && getTestCommonNode()
            .equals(other.getTestCommonNode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestCommonNode()) {
        hash = (37 * hash) + TESTCOMMONNODE_FIELD_NUMBER;
        hash = (53 * hash) + getTestCommonNode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.Packet2.Test2Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Packet2.Test2Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Packet2.Test2Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Packet2.Test2Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Packet2.Test2Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.Packet2.Test2Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.Packet2.Test2Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.Packet2.Test2Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.Packet2.Test2Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.Packet2.Test2Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.Packet2.Test2Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.Packet2.Test2Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.Packet2.Test2Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Test2Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.Test2Response)
        test.Packet2.Test2ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.Packet2.internal_static_test_Test2Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.Packet2.internal_static_test_Test2Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.Packet2.Test2Response.class, test.Packet2.Test2Response.Builder.class);
      }

      // Construct using test.Packet2.Test2Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (testCommonNodeBuilder_ == null) {
          testCommonNode_ = null;
        } else {
          testCommonNode_ = null;
          testCommonNodeBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.Packet2.internal_static_test_Test2Response_descriptor;
      }

      public test.Packet2.Test2Response getDefaultInstanceForType() {
        return test.Packet2.Test2Response.getDefaultInstance();
      }

      public test.Packet2.Test2Response build() {
        test.Packet2.Test2Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public test.Packet2.Test2Response buildPartial() {
        test.Packet2.Test2Response result = new test.Packet2.Test2Response(this);
        if (testCommonNodeBuilder_ == null) {
          result.testCommonNode_ = testCommonNode_;
        } else {
          result.testCommonNode_ = testCommonNodeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.Packet2.Test2Response) {
          return mergeFrom((test.Packet2.Test2Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.Packet2.Test2Response other) {
        if (other == test.Packet2.Test2Response.getDefaultInstance()) return this;
        if (other.hasTestCommonNode()) {
          mergeTestCommonNode(other.getTestCommonNode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.Packet2.Test2Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.Packet2.Test2Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private common.Common.CommonNode testCommonNode_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          common.Common.CommonNode, common.Common.CommonNode.Builder, common.Common.CommonNodeOrBuilder> testCommonNodeBuilder_;
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      public boolean hasTestCommonNode() {
        return testCommonNodeBuilder_ != null || testCommonNode_ != null;
      }
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      public common.Common.CommonNode getTestCommonNode() {
        if (testCommonNodeBuilder_ == null) {
          return testCommonNode_ == null ? common.Common.CommonNode.getDefaultInstance() : testCommonNode_;
        } else {
          return testCommonNodeBuilder_.getMessage();
        }
      }
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      public Builder setTestCommonNode(common.Common.CommonNode value) {
        if (testCommonNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          testCommonNode_ = value;
          onChanged();
        } else {
          testCommonNodeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      public Builder setTestCommonNode(
          common.Common.CommonNode.Builder builderForValue) {
        if (testCommonNodeBuilder_ == null) {
          testCommonNode_ = builderForValue.build();
          onChanged();
        } else {
          testCommonNodeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      public Builder mergeTestCommonNode(common.Common.CommonNode value) {
        if (testCommonNodeBuilder_ == null) {
          if (testCommonNode_ != null) {
            testCommonNode_ =
              common.Common.CommonNode.newBuilder(testCommonNode_).mergeFrom(value).buildPartial();
          } else {
            testCommonNode_ = value;
          }
          onChanged();
        } else {
          testCommonNodeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      public Builder clearTestCommonNode() {
        if (testCommonNodeBuilder_ == null) {
          testCommonNode_ = null;
          onChanged();
        } else {
          testCommonNode_ = null;
          testCommonNodeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      public common.Common.CommonNode.Builder getTestCommonNodeBuilder() {
        
        onChanged();
        return getTestCommonNodeFieldBuilder().getBuilder();
      }
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      public common.Common.CommonNodeOrBuilder getTestCommonNodeOrBuilder() {
        if (testCommonNodeBuilder_ != null) {
          return testCommonNodeBuilder_.getMessageOrBuilder();
        } else {
          return testCommonNode_ == null ?
              common.Common.CommonNode.getDefaultInstance() : testCommonNode_;
        }
      }
      /**
       * <code>.common.CommonNode testCommonNode = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          common.Common.CommonNode, common.Common.CommonNode.Builder, common.Common.CommonNodeOrBuilder> 
          getTestCommonNodeFieldBuilder() {
        if (testCommonNodeBuilder_ == null) {
          testCommonNodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              common.Common.CommonNode, common.Common.CommonNode.Builder, common.Common.CommonNodeOrBuilder>(
                  getTestCommonNode(),
                  getParentForChildren(),
                  isClean());
          testCommonNode_ = null;
        }
        return testCommonNodeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.Test2Response)
    }

    // @@protoc_insertion_point(class_scope:test.Test2Response)
    private static final test.Packet2.Test2Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.Packet2.Test2Response();
    }

    public static test.Packet2.Test2Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test2Response>
        PARSER = new com.google.protobuf.AbstractParser<Test2Response>() {
      public Test2Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test2Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test2Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test2Response> getParserForType() {
      return PARSER;
    }

    public test.Packet2.Test2Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code test.Test2Service}
   */
  public static abstract class Test2Service
      implements com.google.protobuf.Service {
    protected Test2Service() {}

    public interface Interface {
      /**
       * <code>rpc Test222(.test.Test2Request) returns (.test.Test2Response);</code>
       */
      public abstract void test222(
          com.google.protobuf.RpcController controller,
          test.Packet2.Test2Request request,
          com.google.protobuf.RpcCallback<test.Packet2.Test2Response> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new Test2Service() {
        @java.lang.Override
        public  void test222(
            com.google.protobuf.RpcController controller,
            test.Packet2.Test2Request request,
            com.google.protobuf.RpcCallback<test.Packet2.Test2Response> done) {
          impl.test222(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.test222(controller, (test.Packet2.Test2Request)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return test.Packet2.Test2Request.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return test.Packet2.Test2Response.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc Test222(.test.Test2Request) returns (.test.Test2Response);</code>
     */
    public abstract void test222(
        com.google.protobuf.RpcController controller,
        test.Packet2.Test2Request request,
        com.google.protobuf.RpcCallback<test.Packet2.Test2Response> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return test.Packet2.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.test222(controller, (test.Packet2.Test2Request)request,
            com.google.protobuf.RpcUtil.<test.Packet2.Test2Response>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return test.Packet2.Test2Request.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return test.Packet2.Test2Response.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends test.Packet2.Test2Service implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void test222(
          com.google.protobuf.RpcController controller,
          test.Packet2.Test2Request request,
          com.google.protobuf.RpcCallback<test.Packet2.Test2Response> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          test.Packet2.Test2Response.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            test.Packet2.Test2Response.class,
            test.Packet2.Test2Response.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public test.Packet2.Test2Response test222(
          com.google.protobuf.RpcController controller,
          test.Packet2.Test2Request request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public test.Packet2.Test2Response test222(
          com.google.protobuf.RpcController controller,
          test.Packet2.Test2Request request)
          throws com.google.protobuf.ServiceException {
        return (test.Packet2.Test2Response) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          test.Packet2.Test2Response.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:test.Test2Service)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test2Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test2Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test2Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test2Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpacket2.proto\022\004test\032\014common.proto\"\036\n\014T" +
      "est2Request\022\016\n\006testId\030\001 \001(\005\";\n\rTest2Resp" +
      "onse\022*\n\016testCommonNode\030\001 \001(\0132\022.common.Co" +
      "mmonNode2B\n\014Test2Service\0222\n\007Test222\022\022.te" +
      "st.Test2Request\032\023.test.Test2ResponseB\003\210\001" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.Common.getDescriptor(),
        }, assigner);
    internal_static_test_Test2Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_Test2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test2Request_descriptor,
        new java.lang.String[] { "TestId", });
    internal_static_test_Test2Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_Test2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test2Response_descriptor,
        new java.lang.String[] { "TestCommonNode", });
    common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
