// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Test {

  /// <summary>Holder for reflection information generated from services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zZXJ2aWNlcy5wcm90bxIEdGVzdBoMcGFja2V0LnByb3RvGg1wYWNrZXQy",
            "LnByb3RvMmsKBkhhbmRsZRItCgRUZXN0EhEudGVzdC5UZXN0UmVxdWVzdBoS",
            "LnRlc3QuVGVzdFJlc3BvbnNlEjIKB1Rlc3QyMjISEi50ZXN0LlRlc3QyUmVx",
            "dWVzdBoTLnRlc3QuVGVzdDJSZXNwb25zZUIDiAEBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Test.PacketReflection.Descriptor, global::Test.Packet2Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
