// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoCenterGame {

  /// <summary>Holder for reflection information generated from services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zZXJ2aWNlcy5wcm90bxIPcHJvdG9DZW50ZXJHYW1lGgxjb21tb24ucHJv",
            "dG8aCnRlc3QucHJvdG8aDnJlZ2lzdGVyLnByb3RvMtcBCgdIYW5kbGVyEkMK",
            "BFRlc3QSHC5wcm90b0NlbnRlckdhbWUuVGVzdFJlcXVlc3QaHS5wcm90b0Nl",
            "bnRlckdhbWUuVGVzdFJlc3BvbnNlEkQKCFRlc3RQdXNoEhUucHJvdG9DZW50",
            "ZXJHYW1lLlZvaWQaIS5wcm90b0NlbnRlckdhbWUuVGVzdFB1c2hSZXNwb25z",
            "ZRJBCgdCaW5kTXNnEh8ucHJvdG9DZW50ZXJHYW1lLkJpbmRNc2dSZXF1ZXN0",
            "GhUucHJvdG9DZW50ZXJHYW1lLlZvaWRCA4gBAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ProtoCenterGame.CommonReflection.Descriptor, global::ProtoCenterGame.TestReflection.Descriptor, global::ProtoCenterGame.RegisterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
