// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Test {

  /// <summary>Holder for reflection information generated from services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zZXJ2aWNlcy5wcm90bxIEdGVzdBoMY29tbW9uLnByb3RvGgxwYWNrZXQu",
            "cHJvdG8aDXBhY2tldDIucHJvdG8ynAEKB0hhbmRsZXISLQoEVGVzdBIRLnRl",
            "c3QuVGVzdFJlcXVlc3QaEi50ZXN0LlRlc3RSZXNwb25zZRIyCgdUZXN0MjIy",
            "EhIudGVzdC5UZXN0MlJlcXVlc3QaEy50ZXN0LlRlc3QyUmVzcG9uc2USLgoI",
            "VGVzdFB1c2gSCi50ZXN0LlZvaWQaFi50ZXN0LlRlc3RQdXNoUmVzcG9uc2VC",
            "A4gBAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Test.CommonReflection.Descriptor, global::Test.PacketReflection.Descriptor, global::Test.Packet2Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
